const APP_BAR_HEIGHT = 48;
const BOARD_BAR_HEIGHT = 56;
const COLUMN_HEADER_HEIGHT = 50;
const COLUMN_FOOTER_HEIGHT = 56;

export {
  APP_BAR_HEIGHT,
  BOARD_BAR_HEIGHT,
  COLUMN_FOOTER_HEIGHT,
  COLUMN_HEADER_HEIGHT,
};
